version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: ratzcraft-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ratzcraft
      POSTGRES_PASSWORD: ratzcraft
      POSTGRES_DB: ratzcraft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: